### ISSUE TITLE
Trigger end-to-end tests on successful Vercel build

### ISSUE THREAD

**Issue by barbarah** [colonial-heritage/colonial-collections#132]
The end-to-end tests sometimes fail because they stop waiting for the Vercel build. So the end-to-end tests need to be triggered correctly.

# Option 1 (current situation): Wait x seconds and then run tests

Very error prone. Builds are often queued, and therefore difficult to predict how long the job will have to wait.

Example of one workflow:
```
name: End-to-end testing Dataset Browser

on:
  pull_request:
    branches: ["main"]
    paths:
      - "package.json"
      - "apps/dataset-browser/**"
      - ".github/workflows/end-to-end-testing-dataset-browser.yml"
      - "packages/**"

jobs:
  run-end-to-end-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Wait for a successful Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForPreview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 180
          environment: Preview – colonial-collections-dataset-browser
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Cypress for Dataset Browser 🌲
        uses: cypress-io/github-action@v5
        with:
          project: ./apps/dataset-browser
          wait-on: ${{ steps.waitForPreview.outputs.url }}
        env:
          CYPRESS_BASE_URL: ${{ steps.waitForPreview.outputs.url }}
```

# Option 2: A workflow with two jobs triggered by deployment_status.

This workflow is triggered by deployment_status, with an if statement.

This job is triggered twice by both Vercel builds, but only the last job is visible in the review output:

![image](https://github.com/colonial-heritage/colonial-collections/assets/1481602/7c83945d-246b-4f3a-b049-961e8d1d3ca3)

The workflow:
```
name: End-to-end testing
on:
  [deployment_status]
jobs:     
  researcher-job:
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'Preview – colonial-collections-researcher'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Cypress for Researcher 🌲
        uses: cypress-io/github-action@v5
        with:
          project: ./apps/researcher
          wait-on: ${{ github.event.deployment_status.target_url }}
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}

  dataset-browser-job:
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'Preview – colonial-collections-dataset-browser'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Cypress for Dataset Browser 🌲
        uses: cypress-io/github-action@v5
        with:
          project: ./apps/dataset-browser
          wait-on: ${{ github.event.deployment_status.target_url }}
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
```

# Option 3: Two workflows with two jobs triggered by deployment_status.

Very similar to option 2. But then with a dedicated workflow per app.

This will show both workflows but only the last trigger. Even if the last workflow was skipped.

![image](https://github.com/colonial-heritage/colonial-collections/assets/1481602/5d642f51-6694-46c4-a360-07fc9668a1f5)

Example of one workflow:
```
name: End-to-end testing Dataset Browser
on:
  [deployment_status]
jobs:     
  run-end-to-end-tests:
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'Preview – colonial-collections-dataset-browser'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Cypress for Dataset Browser 🌲
        uses: cypress-io/github-action@v5
        with:
          project: ./apps/dataset-browser
          wait-on: ${{ github.event.deployment_status.target_url }}
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
```

# Option 4: Move configuration of Vercel to github actions

I tried this using the official docs: https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

```
name: Vercel Preview Deployment Dataset Browser
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
```

The problem is the build could not find the packages inside the turbo repo. I think because it runs `npm run build` inside the `apps/dataset-browser` instead of `npm run turbo`. The build script cannot be easily changed.
